# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Thibault MARTIN
  url:        http://www.thibaultmart.in

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
permalink: pretty
