# Setup
title:        Improvement by failure
tagline:      Because hey, we're hoomans
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Thibault MARTIN
  url:        http://www.thibaultmart.in

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
permalink: pretty
